name: Integration Tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["node-cjs"]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build SDK
        run: bun run build

      - name: Pack SDK
        run: |
          # Temporarily remove symlink to avoid npm pack issues
          rm -f README.md
          cd src
          npm pack --pack-destination ../
          cd ../
          # Restore symlink
          ln -s ./src/README.md README.md

      - name: Test ${{ matrix.environment }} integration
        run: |
          case "${{ matrix.environment }}" in
            "node-cjs")
              echo "Testing Node CommonJS integration..."
              mkdir -p integration-test/node-cjs
              cd integration-test/node-cjs
              
              # Initialize basic Node project
              npm init -y
              
              # Install the packed SDK
              npm install ../../rhinestone-sdk-*.tgz
              
              # Create test script
              cat > index.js << 'EOF'
          const sdk = require('@rhinestone/sdk');
          console.log('✓ SDK imported successfully');

          // Basic smoke test - just try to access main exports
          if (typeof sdk === 'object' && sdk !== null) {
            console.log('✓ SDK is an object');
          } else {
            console.error('✗ SDK import failed - not an object');
            process.exit(1);
          }

          console.log('✓ Node CommonJS integration test passed');
          EOF
              
              # Run the test
              node index.js
              ;;
          esac
