name: Integration Tests (Reusable)

on:
  workflow_call:

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["node-cjs", "node-esm", "react-native"]

    steps:
      # Setup and Build
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build SDK
        run: bun run build

      # Package SDK for Testing
      - name: Pack SDK
        run: |
          # Create a clean workspace for packing
          mkdir -p /tmp/sdk-pack
          cp -r src/* /tmp/sdk-pack/
          cd /tmp/sdk-pack
          npm pack --pack-destination $GITHUB_WORKSPACE/

      # Run Integration Tests
      - name: Test ${{ matrix.environment }} integration
        run: ./.github/scripts/test-${{ matrix.environment }}.sh
