name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  integration-tests:
    name: Integration Tests
    uses: ./.github/workflows/integration-reusable.yaml