name: Integration Tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["node-cjs", "node-esm"]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build SDK
        run: bun run build

      - name: Pack SDK
        run: |
          # Create a clean workspace for packing
          mkdir -p /tmp/sdk-pack
          cp -r src/* /tmp/sdk-pack/
          cd /tmp/sdk-pack
          npm pack --pack-destination $GITHUB_WORKSPACE/

      - name: Test ${{ matrix.environment }} integration
        run: |
          case "${{ matrix.environment }}" in
            "node-cjs")
              echo "Testing Node CommonJS integration..."
              
              # Create test directory completely outside the repo
              mkdir -p /tmp/integration-test/node-cjs
              cd /tmp/integration-test/node-cjs
              
              # Initialize basic Node project
              npm init -y
              
              # Install the packed SDK using absolute path
              npm install $GITHUB_WORKSPACE/rhinestone-sdk-*.tgz
              
              # Create test script
              cat > index.js << 'EOF'
          const sdk = require('@rhinestone/sdk');
          console.log('✓ SDK imported successfully');

          // Basic smoke test - just try to access main exports
          if (typeof sdk === 'object' && sdk !== null) {
            console.log('✓ SDK is an object');
          } else {
            console.error('✗ SDK import failed - not an object');
            process.exit(1);
          }

          console.log('✓ Node CommonJS integration test passed');
          EOF
              
              # Run the test
              node index.js
              ;;
            "node-esm")
              echo "Testing Node ESM integration..."
              
              # Create test directory completely outside the repo
              mkdir -p /tmp/integration-test/node-esm
              cd /tmp/integration-test/node-esm
              
              # Initialize basic Node project with ESM
              npm init -y
              # Set package type to module for ESM
              npm pkg set type=module
              
              # Install the packed SDK using absolute path
              npm install $GITHUB_WORKSPACE/rhinestone-sdk-*.tgz
              
              # Create test script
              cat > index.js << 'EOF'
          import sdk from '@rhinestone/sdk';
          console.log('✓ SDK imported successfully');
          
          // Basic smoke test - just try to access main exports
          if (typeof sdk === 'object' && sdk !== null) {
            console.log('✓ SDK is an object');
          } else {
            console.error('✗ SDK import failed - not an object');
            process.exit(1);
          }
          
          console.log('✓ Node ESM integration test passed');
          EOF
              
              # Run the test
              node index.js
              ;;
          esac
